# Generated by Django 5.0.7 on 2024-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('max_length', models.IntegerField()),
                ('required', models.BooleanField()),
                ('type', models.CharField(choices=[('integer', 'Integer'), ('string', 'String'), ('text', 'Text'), ('list', 'List'), ('video', 'Video'), ('image', 'Image'), ('geolocation', 'Geolocation')], max_length=255)),
                ('provider_labels', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Yetkazib berish narxi')),
                ('status', models.CharField(choices=[('in_processing', 'In Process'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('performing', 'Performing'), ('performed', 'Performed'), ('refunded', 'Refunded')], max_length=20, verbose_name='Order Statusi')),
                ('paid', models.BooleanField(db_default=False, verbose_name="To'lov qilingan yoki yo'qligi")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazib berish vaqti')),
                ('delivery_type', models.CharField(choices=[('online_delivery', 'Online Delivery'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=50)),
                ('order_type', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web')], max_length=20)),
                ('is_archived', models.BooleanField(db_default=False, verbose_name='Arxivlangan buyurtmalar')),
                ('yandex_taxi_link', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('entrance', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kirish joyi')),
                ('door_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='eshik telfon raqami')),
                ('floor_number', models.IntegerField(blank=True, null=True, verbose_name='Qavat raqami')),
                ('apartment_number', models.IntegerField(blank=True, null=True, verbose_name='kvartera raqami')),
                ('first_name', models.CharField(max_length=50, verbose_name='Haridorni ismi')),
                ('last_name', models.CharField(max_length=50, verbose_name='Haridorni familiyasi')),
                ('phone', models.CharField(max_length=50, verbose_name='Haridorni telfon raqami ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma yaratilgan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(db_default=1, verbose_name='Soni')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Faolligi')),
                ('code', models.CharField(max_length=255, verbose_name='Promokod')),
                ('start_date', models.DateTimeField(verbose_name='Amal qilish muddati(boshi)')),
                ('end_date', models.DateTimeField(verbose_name='Amal qilish muddati(oxiri)')),
                ('limit', models.IntegerField(verbose_name='Soni')),
                ('remaining_quantity', models.IntegerField(verbose_name='Qolgan miqdor')),
                ('type', models.CharField(choices=[('free_delivery', 'Free delivery'), ('discount', 'Discount')], default='free_delivery', max_length=255, verbose_name='Tur')),
                ('percent', models.IntegerField(db_default=0)),
                ('used_quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('delivery', 'Delivery'), ('payment', 'Payment')], max_length=15)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('inplace', 'Inplace'), ('telegram', 'Telegram'), ('web', 'Web'), ('instalment', 'Instalment')], max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='tavsifi')),
            ],
        ),
        migrations.CreateModel(
            name='ShopService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('not_exists', 'Not exists')], db_default='inactive', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShopServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=dict)),
            ],
        ),
    ]
